### PR TITLE
Use OSDynamicCast instead of reinterpret_case

### PR DESCRIPTION
**Pull request by lvs1974**

### CODE REVIEW

**Comment by Goshin** [comment]
With this commit, I got a link error when loading kext.

`kextutil -v VoodooI2CHID.kext -d VoodooI2C.kext` shows:
```
Code Signing Failure: code signature is invalid
./Build/Products/Release/test/VoodooI2CHID.kext appears to be loadable (not including linkage for on-disk libraries).
Loading ./Build/Products/Release/test/VoodooI2CHID.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) kxld[com.alexandred.VoodooI2CHID]: The following symbols are unresolved for this kext:
(kernel) kxld[com.alexandred.VoodooI2CHID]: 	__ZN13IOFramebuffer9metaClassE
(kernel) Can't load kext com.alexandred.VoodooI2CHID - link failed.
(kernel) Failed to load executable for kext com.alexandred.VoodooI2CHID.
(kernel) Kext com.alexandred.VoodooI2CHID failed to load (0xdc008016).
(kernel) Failed to load kext com.alexandred.VoodooI2CHID (error 0xdc008016).
Failed to load ./Build/Products/Release/test/VoodooI2CHID.kext - (libkern/kext) link error.
Failed to load ./Build/Products/Release/test/VoodooI2CHID.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
```

**Comment by kprinssu** [comment]
@Goshin seems like https://github.com/alexandred/VoodooI2CHID/pull/21 rather than this PR. Framebuffer kext dependency was removed in there.

**Comment by lvs1974** [comment]
@Goshin, in my setup it works:
`sudo chown -R root:wheel VoodooI2C*
sudo chmod -R 755 VoodooI2C*
sudo kextutil -v VoodooI2CHID.kext -d VoodooI2C.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signature (-67050) allowed: <OSKext 0x7fda2242ed70 [0x7fff897268c0]> { URL = "file:///Temp/VoodooI2CHID.kext/", ID = "com.alexandred.VoodooI2CHID" }
Kext with invalid signature (-67050) allowed: <OSKext 0x7fda22433140 [0x7fff897268c0]> { URL = "file:///Temp/VoodooI2C.kext/", ID = "com.alexandred.VoodooI2C" }
Kext with invalid signature (-67050) allowed: <OSKext 0x7fda22426810 [0x7fff897268c0]> { URL = "file:///Temp/VoodooI2C.kext/Contents/PlugIns/VoodooI2CServices.kext/", ID = "com.alexandred.VoodooI2CServices" }
Kext with invalid signature (-67050) allowed: <OSKext 0x7fda22411880 [0x7fff897268c0]> { URL = "file:///Temp/VoodooI2C.kext/Contents/PlugIns/VoodooGPIO.kext/", ID = "org.coolstar.VoodooGPIO" }
Code Signing Failure: code signature is invalid
/Temp/VoodooI2CHID.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Temp/VoodooI2CHID.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) Refusing new kext com.alexandred.VoodooI2C, v2.3: a loaded copy with a different executable UUID is already present.
/Temp/VoodooI2CHID.kext successfully loaded (or already loaded).
Invalid signature -67050 for kext <OSKext 0x7fda2242ed70 [0x7fff897268c0]> { URL = "file:///Temp/VoodooI2CHID.kext/", ID = "com.alexandred.VoodooI2CHID" }`

Xcode: 11.3.1

**Comment by Goshin** [comment]
> @Goshin seems like #21 rather than this PR. Framebuffer kext dependency was removed in there.

I can confirm it is this commit that causes the error. Perhaps it has something to do with the Xcode 11.4. 

Catalina 10.15.4 + Xcode 11.4

**Comment by lvs1974** [comment]
I would suggest to use old and reliable reinterpret_cast instead of OSDynamicCast.
Probably when we use OSDynamicCast - class must be linked via dependency,
But for reinterpret_case it is not necessary.

**Comment by kprinssu** [comment]
Reverted the old commit.

**Pull request merged**
