### PR TITLE
Fix laggy trackpad after polling mode optimisation commit

### PR DESCRIPTION
**Pull request by lvs1974**
This is a fix for https://github.com/alexandred/VoodooI2C/issues/269.

### CODE REVIEW

**Comment by kprinssu** [comment]
I'll sync changes to VoodooI2C master once we get a fix for https://github.com/alexandred/VoodooI2C/issues/269#issuecomment-608402938

**Comment by lvs1974** [comment]
@kprinssu, my fix in VoodooI2CHID has nothing to do with issue which can be observed by @Mateo1234454545. It is something what we are trying to find out.

**Comment by kprinssu** [comment]
@lvs1974 looks like removing the IOWorkLoop from @erictoby was the cause. Let's carry the discussion on there.

**Comment by lvs1974** [comment]
@kprinssu, I think we do not need to fix anything else here.
You can read discussion in 269, and there were issues since release 2.1.

**Pull request merged**
